import {fontFamily} from 'tailwindcss/defaultTheme'


module.exports = {
  darkMode: 'class',
  content: [
    // './renderer/app/**/*.{js,ts,jsx,tsx}',
    // './renderer/(providers)/**/*.{js,ts,jsx,tsx}',
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    colors: {
      // use colors only specified
      // white: colors.white,
      // gray: colors.gray,
      // blue: colors.blue,
    },
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--twc-gray-50))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--twc-red-200))',
          foreground: 'hsl(var(--twc-red-900))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        gray: {
          50: 'hsl(var(--twc-gray-50))',
          100: 'hsl(var(--twc-gray-100))',
          200: 'hsl(var(--twc-gray-200))',
          300: 'hsl(var(--twc-gray-300))',
          400: 'hsl(var(--twc-gray-400))',
          500: 'hsl(var(--twc-gray-500))',
          600: 'hsl(var(--twc-gray-600))',
          700: 'hsl(var(--twc-gray-700))',
          800: 'hsl(var(--twc-gray-800))',
          900: 'hsl(var(--twc-gray-900))',
        },
        red: {
          50: 'hsl(var(--twc-red-50))',
          100: 'hsl(var(--twc-red-100))',
          200: 'hsl(var(--twc-red-200))',
          300: 'hsl(var(--twc-red-300))',
          400: 'hsl(var(--twc-red-400))',
          500: 'hsl(var(--twc-red-500))',
          600: 'hsl(var(--twc-red-600))',
          700: 'hsl(var(--twc-red-700))',
          800: 'hsl(var(--twc-red-800))',
          900: 'hsl(var(--twc-red-900))',
        },
        yellow: {
          50: 'hsl(var(--twc-yellow-50))',
          100: 'hsl(var(--twc-yellow-100))',
          200: 'hsl(var(--twc-yellow-200))',
          300: 'hsl(var(--twc-yellow-300))',
          400: 'hsl(var(--twc-yellow-400))',
          500: 'hsl(var(--twc-yellow-500))',
          600: 'hsl(var(--twc-yellow-600))',
          700: 'hsl(var(--twc-yellow-700))',
          800: 'hsl(var(--twc-yellow-800))',
          900: 'hsl(var(--twc-yellow-900))',
        },
        orange: {
          50: 'hsl(var(--twc-orange-50))',
          100: 'hsl(var(--twc-orange-100))',
          200: 'hsl(var(--twc-orange-200))',
          300: 'hsl(var(--twc-orange-300))',
          400: 'hsl(var(--twc-orange-400))',
          500: 'hsl(var(--twc-orange-500))',
          600: 'hsl(var(--twc-orange-600))',
          700: 'hsl(var(--twc-orange-700))',
          800: 'hsl(var(--twc-orange-800))',
          900: 'hsl(var(--twc-orange-900))',
        },
        green: {
          50: 'hsl(var(--twc-green-50))',
          100: 'hsl(var(--twc-green-100))',
          200: 'hsl(var(--twc-green-200))',
          300: 'hsl(var(--twc-green-300))',
          400: 'hsl(var(--twc-green-400))',
          500: 'hsl(var(--twc-green-500))',
          600: 'hsl(var(--twc-green-600))',
          700: 'hsl(var(--twc-green-700))',
          800: 'hsl(var(--twc-green-800))',
          900: 'hsl(var(--twc-green-900))',
        },
        blue: {
          50: 'hsl(var(--twc-blue-50))',
          100: 'hsl(var(--twc-blue-100))',
          200: 'hsl(var(--twc-blue-200))',
          300: 'hsl(var(--twc-blue-300))',
          400: 'hsl(var(--twc-blue-400))',
          500: 'hsl(var(--twc-blue-500))',
          600: 'hsl(var(--twc-blue-600))',
          700: 'hsl(var(--twc-blue-700))',
          800: 'hsl(var(--twc-blue-800))',
          900: 'hsl(var(--twc-blue-900))',
        },
        indigo: {
          50: 'hsl(var(--twc-indigo-50))',
          100: 'hsl(var(--twc-indigo-100))',
          200: 'hsl(var(--twc-indigo-200))',
          300: 'hsl(var(--twc-indigo-300))',
          400: 'hsl(var(--twc-indigo-400))',
          500: 'hsl(var(--twc-indigo-500))',
          600: 'hsl(var(--twc-indigo-600))',
          700: 'hsl(var(--twc-indigo-700))',
          800: 'hsl(var(--twc-indigo-800))',
          900: 'hsl(var(--twc-indigo-900))',
        },
        purple: {
          50: 'hsl(var(--twc-purple-50))',
          100: 'hsl(var(--twc-purple-100))',
          200: 'hsl(var(--twc-purple-200))',
          300: 'hsl(var(--twc-purple-300))',
          400: 'hsl(var(--twc-purple-400))',
          500: 'hsl(var(--twc-purple-500))',
          600: 'hsl(var(--twc-purple-600))',
          700: 'hsl(var(--twc-purple-700))',
          800: 'hsl(var(--twc-purple-800))',
          900: 'hsl(var(--twc-purple-900))',
        },
        pink: {
          50: 'hsl(var(--twc-pink-50))',
          100: 'hsl(var(--twc-pink-100))',
          200: 'hsl(var(--twc-pink-200))',
          300: 'hsl(var(--twc-pink-300))',
          400: 'hsl(var(--twc-pink-400))',
          500: 'hsl(var(--twc-pink-500))',
          600: 'hsl(var(--twc-pink-600))',
          700: 'hsl(var(--twc-pink-700))',
          800: 'hsl(var(--twc-pink-800))',
          900: 'hsl(var(--twc-pink-900))',
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', ...fontFamily.sans],
      },
      keyframes: {
        'accordion-down': {
          from: {height: '0'},
          to: {height: 'var(--radix-accordion-content-height)'},
        },
        'accordion-up': {
          from: {height: 'var(--radix-accordion-content-height)'},
          to: {height: '0'},
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },

    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/typography'),
    require('tailwind-scrollbar')({nocompatible: true}),
  ],
}